use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use serde_json::{json, Map};
use walkdir::WalkDir;

use super::agent_roles::CodexAgentRole;
use super::{
    escape_toml_string, first_heading, is_executable, is_ignored_path, normalize_generated_bytes,
    normalize_generated_text, strip_leading_frontmatter, yaml_scalar, PlannedFile,
};

pub(super) fn read_claude_env(claude_dir: &Path) -> Result<BTreeMap<String, String>> {
    let settings_path = claude_dir.join("settings.json");
    let settings: serde_json::Value = serde_json::from_slice(
        &fs::read(&settings_path)
            .with_context(|| format!("failed to read {}", settings_path.display()))?,
    )
    .with_context(|| format!("failed to parse {}", settings_path.display()))?;

    let mut env = BTreeMap::new();
    if let Some(object) = settings.get("env").and_then(serde_json::Value::as_object) {
        for (key, value) in object {
            if let Some(value) = value.as_str() {
                env.insert(key.clone(), value.to_owned());
            }
        }
    }
    Ok(env)
}

pub(super) fn codex_config(
    env: &BTreeMap<String, String>,
    agent_roles: &[CodexAgentRole],
    footer: Option<&str>,
) -> String {
    let mut toml = String::from(
        r#"#:schema https://developers.openai.com/codex/config-schema.json

# Generated by `cargo run -p codex-env -- mirror`.
approval_policy = "on-request"
sandbox_mode = "workspace-write"
web_search = "live"
model_context_window = 4000000

[mcp_servers.github]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-github"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

[mcp_servers.exa]
url = "https://mcp.exa.ai/mcp"

[mcp_servers.memory]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-memory"]

[mcp_servers.playwright]
command = "npx"
args = ["-y", "@playwright/mcp@latest", "--extension"]

[mcp_servers.sequential-thinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp_servers.claude-flow]
command = "npx"
args = ["@claude-flow/cli@latest", "mcp", "start"]

[mcp_servers.claude-flow.env]
CLAUDE_FLOW_MODE = "v3"
CLAUDE_FLOW_HOOKS_ENABLED = "true"
CLAUDE_FLOW_TOPOLOGY = "hierarchical-mesh"
CLAUDE_FLOW_MAX_AGENTS = "15"
CLAUDE_FLOW_MEMORY_BACKEND = "hybrid"

[features]
multi_agent = true

[skills]
include_instructions = true

[agents]
max_threads = 15
max_depth = 3

[agents.explorer]
description = "Read-only codebase explorer for gathering evidence before changes are proposed."
config_file = "agents/explorer.toml"

[agents.reviewer]
description = "PR reviewer focused on correctness, security, and missing tests."
config_file = "agents/reviewer.toml"

[agents.docs_researcher]
description = "Documentation specialist that verifies APIs, framework behavior, and release-note claims against primary documentation."
config_file = "agents/docs-researcher.toml"
"#,
    );

    for role in agent_roles {
        toml.push_str(&format!(
            "\n[agents.{}]\ndescription = \"{}\"\nconfig_file = \"{}\"\n",
            role.role_name,
            escape_toml_string(&role.description),
            escape_toml_string(&role.config_file.display().to_string())
        ));
    }

    toml.push_str(
        r#"
[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
"#,
    );

    for (key, value) in env {
        toml.push_str(&format!("{key} = \"{}\"\n", escape_toml_string(value)));
    }

    if let Some(footer) = footer {
        toml.push('\n');
        toml.push_str(footer.trim());
        toml.push('\n');
    }

    toml
}

pub(super) fn codex_agents_md() -> String {
    String::from(
        r#"# Codex Mirror Surface

This directory is generated from the tracked `.claude` surface by the Rust
`codex-env` harness.

## Refresh

```bash
cargo run -p codex-env -- mirror
cargo run -p codex-env -- mirror --check
```

## Mirrored Surfaces

- `.claude/**` -> `.codex/mirror/.claude/**` byte-for-byte
- `.claude/**` -> `.codex/mirror-symbols.json` deterministic file/symbol inventory
- `.claude/settings.json` -> `.codex/hooks.json` and shell environment defaults
- `.claude/hooks/` -> `.codex/hooks/`
- `.claude/skills/` -> `.agents/skills/`
- `.claude/commands/**/*.md` -> `.agents/skills/source-command-*`
- `.claude/commands/**/*.md` -> `.codex/prompts/*.md` for `/prompts:*`

Use `--lua-policy <path>` when a repo-local transformation is needed. The Lua
script receives a `mirror` table with `repo_root` and `claude_dir`, and may
return `{ config_footer = "...", skill_prelude = "..." }`.

## Install Prompt Commands

Codex loads custom prompts from `$CODEX_HOME/prompts`, not directly from a
repository. After refreshing this mirror, install the generated prompt commands
with:

```bash
.codex/helpers/install-prompts.sh
```

Restart Codex after installing. The Claude command mirrors then appear as Codex
prompt commands such as `/prompts:sparc-code` and
`/prompts:claude-flow-swarm`.
"#,
    )
}

pub(super) fn codex_agent_profiles(codex_dir: &Path) -> Vec<PlannedFile> {
    [
        (
            "explorer.toml",
            "explorer",
            "Read-only codebase explorer for gathering evidence before changes are proposed.",
            "gpt-5.4",
            "medium",
            "Stay in exploration mode.\nTrace the real execution path, cite files and symbols, and avoid proposing fixes unless the parent agent asks for them.\nPrefer targeted search and file reads over broad scans.\n",
        ),
        (
            "reviewer.toml",
            "reviewer",
            "PR reviewer focused on correctness, security, and missing tests.",
            "gpt-5.4",
            "high",
            "Review like an owner.\nPrioritize correctness, security, behavioral regressions, and missing tests.\nLead with concrete findings and avoid style-only feedback unless it hides a real bug.\n",
        ),
        (
            "docs-researcher.toml",
            "docs-researcher",
            "Documentation specialist that verifies APIs, framework behavior, and release-note claims against primary documentation.",
            "gpt-5.4",
            "medium",
            "Verify APIs, framework behavior, and release-note claims against primary documentation before changes land.\nCite the exact docs or file paths that support each claim.\nDo not invent undocumented behavior.\n",
        ),
    ]
    .into_iter()
    .map(
        |(file, name, description, model, effort, instructions)| PlannedFile {
        path: codex_dir.join("agents").join(file),
        bytes: format!(
            "name = \"{}\"\ndescription = \"{}\"\nmodel = \"{model}\"\nmodel_reasoning_effort = \"{effort}\"\nsandbox_mode = \"read-only\"\n\ndeveloper_instructions = \"\"\"\n{instructions}\"\"\"",
            escape_toml_string(name),
            escape_toml_string(description),
        )
        .into_bytes(),
        executable: false,
    },
    )
    .collect()
}

pub(super) fn codex_hooks_json(claude_dir: &Path) -> Result<String> {
    let settings_path = claude_dir.join("settings.json");
    let settings: serde_json::Value = serde_json::from_slice(
        &fs::read(&settings_path)
            .with_context(|| format!("failed to read {}", settings_path.display()))?,
    )?;

    let hooks = normalize_codex_hooks(settings.get("hooks"));
    let output = json!({
        "hooks": hooks,
    });
    Ok(format!("{}\n", serde_json::to_string_pretty(&output)?))
}

fn normalize_codex_hooks(source: Option<&serde_json::Value>) -> serde_json::Value {
    let Some(source) = source.and_then(serde_json::Value::as_object) else {
        return json!({});
    };

    let mut normalized = Map::new();
    for (source_event, groups) in source {
        let Some(codex_event) = codex_hook_event(source_event) else {
            continue;
        };
        let Some(groups) = groups.as_array() else {
            continue;
        };

        let target_groups = normalized
            .entry(codex_event.to_owned())
            .or_insert_with(|| json!([]))
            .as_array_mut()
            .expect("hook event value is initialized as array");

        for group in groups {
            let Some(group_object) = group.as_object() else {
                continue;
            };
            let Some(source_hooks) = group_object
                .get("hooks")
                .and_then(serde_json::Value::as_array)
            else {
                continue;
            };

            let hooks = source_hooks
                .iter()
                .filter_map(normalize_codex_hook_handler)
                .collect::<Vec<_>>();
            if hooks.is_empty() {
                continue;
            }

            let mut target_group = Map::new();
            if let Some(matcher) = group_object
                .get("matcher")
                .and_then(serde_json::Value::as_str)
            {
                target_group.insert("matcher".to_owned(), json!(matcher));
            }
            target_group.insert("hooks".to_owned(), json!(hooks));
            target_groups.push(serde_json::Value::Object(target_group));
        }
    }

    serde_json::Value::Object(normalized)
}

fn codex_hook_event(source_event: &str) -> Option<&'static str> {
    match source_event {
        "SessionStart" => Some("SessionStart"),
        "PreToolUse" => Some("PreToolUse"),
        "PermissionRequest" => Some("PermissionRequest"),
        "PostToolUse" => Some("PostToolUse"),
        "PreCompact" => Some("PreCompact"),
        "PostCompact" => Some("PostCompact"),
        "UserPromptSubmit" => Some("UserPromptSubmit"),
        "SubagentStart" => Some("SubagentStart"),
        "SubagentStop" => Some("SubagentStop"),
        "Stop" | "SessionEnd" => Some("Stop"),
        _ => None,
    }
}

fn normalize_codex_hook_handler(handler: &serde_json::Value) -> Option<serde_json::Value> {
    let handler = handler.as_object()?;
    if handler.get("async").and_then(serde_json::Value::as_bool) == Some(true) {
        return None;
    }
    if handler.get("type").and_then(serde_json::Value::as_str) != Some("command") {
        return None;
    }

    let command = handler.get("command").and_then(serde_json::Value::as_str)?;
    let mut normalized = Map::new();
    normalized.insert("type".to_owned(), json!("command"));
    normalized.insert("command".to_owned(), json!(codex_hook_command(command)));
    if let Some(timeout) = handler.get("timeout").and_then(serde_json::Value::as_u64) {
        normalized.insert(
            "timeout".to_owned(),
            json!(codex_hook_timeout_seconds(timeout)),
        );
    }
    if let Some(status) = handler
        .get("statusMessage")
        .and_then(serde_json::Value::as_str)
    {
        normalized.insert("statusMessage".to_owned(), json!(status));
    }
    Some(serde_json::Value::Object(normalized))
}

fn codex_hook_command(command: &str) -> String {
    let hook_handler = r#"node "${CLAUDE_PROJECT_DIR:-.}/.claude/helpers/hook-handler.cjs" "#;
    if let Some(args) = command.strip_prefix(hook_handler) {
        return format!(
            r#""$(git rev-parse --show-toplevel)/.codex/helpers/run-claude-hook.sh" hook-handler.cjs {}"#,
            args.trim()
        );
    }

    let auto_memory = r#"node "${CLAUDE_PROJECT_DIR:-.}/.claude/helpers/auto-memory-hook.mjs" "#;
    if let Some(args) = command.strip_prefix(auto_memory) {
        return format!(
            r#""$(git rev-parse --show-toplevel)/.codex/helpers/run-claude-hook.sh" auto-memory-hook.mjs {}"#,
            args.trim()
        );
    }

    command.replace(
        "${CLAUDE_PROJECT_DIR:-.}",
        "$(git rev-parse --show-toplevel)",
    )
}

fn codex_hook_timeout_seconds(timeout: u64) -> u64 {
    if timeout > 600 {
        timeout.div_ceil(1000)
    } else {
        timeout
    }
}

pub(super) fn copy_tree_plan(source: &Path, target: &Path) -> Result<Vec<PlannedFile>> {
    if !source.exists() {
        return Ok(Vec::new());
    }

    let mut files = Vec::new();
    for entry in WalkDir::new(source)
        .into_iter()
        .filter_entry(|entry| !is_ignored_path(entry.path()))
    {
        let entry = entry?;
        if !entry.file_type().is_file() {
            continue;
        }
        let relative = entry.path().strip_prefix(source)?;
        let bytes = normalize_generated_bytes(entry.path(), fs::read(entry.path())?);
        files.push(PlannedFile {
            path: target.join(relative),
            bytes,
            executable: is_executable(entry.path())?,
        });
    }
    files.sort_by(|a, b| a.path.cmp(&b.path));
    Ok(files)
}

pub(super) fn command_skill_plan(
    commands_dir: &Path,
    skills_dir: &Path,
    prelude: Option<&str>,
) -> Result<Vec<PlannedFile>> {
    if !commands_dir.exists() {
        return Ok(Vec::new());
    }

    let mut files = Vec::new();
    for entry in WalkDir::new(commands_dir) {
        let entry = entry?;
        if !entry.file_type().is_file()
            || entry.path().extension().and_then(|s| s.to_str()) != Some("md")
        {
            continue;
        }

        let relative = entry.path().strip_prefix(commands_dir)?;
        let stem = relative.with_extension("");
        let name = format!("source-command-{}", super::slugify(&stem.to_string_lossy()));
        let source = fs::read_to_string(entry.path())?;
        let source_body = strip_leading_frontmatter(&source);
        let description = first_heading(&source)
            .unwrap_or_else(|| format!("Workflow command scaffold for {}.", stem.display()));
        let mut body = String::new();
        body.push_str("---\n");
        body.push_str(&format!("name: {name}\n"));
        body.push_str(&format!("description: {}\n", yaml_scalar(&description)));
        body.push_str("---\n\n");
        if let Some(prelude) = prelude {
            body.push_str(prelude.trim());
            body.push_str("\n\n");
        }
        body.push_str(&format!(
            "# /{}\n\nSource: `.claude/commands/{}`\n\n",
            stem.display(),
            relative.display()
        ));
        body.push_str(source_body.trim_start());
        if !body.ends_with('\n') {
            body.push('\n');
        }
        files.push(PlannedFile {
            path: skills_dir.join(name).join("SKILL.md"),
            bytes: normalize_generated_text(&body).into_bytes(),
            executable: false,
        });
    }
    files.sort_by(|a, b| a.path.cmp(&b.path));
    Ok(files)
}
